In [1]:
def clearall():
    all = [var for var in globals() if var[0] != "_"]
    for var in all:
        del globals()[var]
clearall()

In [2]:
print('Importing Librairies...')
import pandas as pd
from colorama import Fore, Back, Style
import time
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
print('Librairies imported')

Importing Librairies...
Librairies imported

In [3]:
___Author___='LumberJack Jyss'
print(" Fin'Lab Depedencies",Fore.BLUE,
      '\n Global Optimized LumberJack Environment Motor',Style.RESET_ALL,'\n GOLEM 55 \n LumberJack Jyss 5779(c)')
print(Fore.BLUE,'째0Oo_D.A.G._26_oO0째',Style.RESET_ALL)
print(" INVESTING.COM'S COMMUNITY SENTIMENTS v1.00")
print('')

 Fin'Lab Depedencies
 Global Optimized LumberJack Environment Motor
 GOLEM 55
 LumberJack Jyss 5779(c)
 째0Oo_D.A.G._26_oO0째
 INVESTING.COM'S COMMUNITY SENTIMENTS v1.00

In [4]:
df_raw = pd.read_csv('InvestingBase.csv')
df = pd.DataFrame()
df['Date'] = df_raw['date']
df['Symbol'] = df_raw['stock_symbol']
df['Name'] = df_raw['pair_name']
df['Sentiment'] = df_raw['call_type']
df.head()

         Date Symbol       Name Sentiment
0  2010-01-27     BA  Boeing Co   Bearish
1  2010-12-15     BA  Boeing Co   Bearish
2  2010-12-27     BA  Boeing Co   Bearish
3  2011-01-25     BA  Boeing Co   Bullish
4  2011-02-25     BA  Boeing Co   Bullish

In [ ]:
tmps1=time.time()
for i in range(0,df.shape[0]):
    print('\r ------Loop : ',i,'/',len(df),'------',end='',flush=True)
    if df.iloc[i,-1] == 'Bearish':
        df.iloc[i,-1] = 0
    else:
        df.iloc[i,-1] = 1
tmps2=round(time.time()-tmps1,2)
print ("Data prepared in = %f" %tmps2,'seconds')
df.head()

 ------Loop :  196509 ------Data prepared in = 0.010000 seconds

In [ ]:
df.to_csv('prepared_data.csv')

In [10]:
df = pd.read_csv('prepared_data.csv')
compteur = pd.read_csv('compteur.csv')
df = df.drop('Unnamed: 0',axis=1)
compteur = compteur.drop('Unnamed: 0',axis=1)

In [18]:
compteur = compteur.sort_values('Sector')
compteur.tail()

    Symb.                              Name     Sector
157   DUK                       Duke Energy  Utilities
371   PPL                         PPL Corp.  Utilities
25    LNT               Alliant Energy Corp  Utilities
344   NRG                        NRG Energy  Utilities
37    AWK  American Water Works Company Inc  Utilities

In [60]:
Consumer_Staples =[]
Energy = []
Financials = []
Health_Care = []
Industrials = []
Information_Technology = []
Materials = []
Real_Estate = []
Telecommunication_Services = []
Utilities = []
SECTOR = [Consumer_Staples,Energy,Financials,Health_Care,Industrials,Information_Technology,Materials,Real_Estate,Telecommunication_Services,Utilities]
a=0
for i in range(1,compteur.shape[0]):
    if compteur.iloc[i,2] != compteur.iloc[i-1,2]:
        a+=1
        SECTOR[a-1].append(compteur.iloc[i,0])
    else:
        SECTOR[a-1].append(compteur.iloc[i,0])

In [83]:
for a, _ in enumerate(SECTOR):
    print('SECTEUR ',a)
    for i , _ in enumerate(SECTOR[a]):
        print(SECTOR[a][i])

SECTEUR  0
EL
MKC
STZ
SYY
GIS
HSY
CLX
COTY
MNST
TAP
CAG
ADM
MO
PG
MDLZ
CPB
KHC
DPS
KR
CL
CVS
BF.B
TSN
PM
KO
K
SJM
HRL
PEP
CHD
KMB
COST
SECTEUR  1
SLB
NOV
EQT
NFX
NBL
MRO
APC
KMI
HP
OXY
OKE
EOG
PSX
HAL
ANDV
FTI
DVN
PXD
RRC
HES
COP
MPC
XOM
XEC
CXO
COG
APA
CVX
BHGE
SECTEUR  2
AXP
RJF
GS
PRU
AIZ
HIG
AMP
PGR
ALL
FITB
COF
HRB
NTRS
BEN
NDAQ
PNC
BAC
BLK
BHF
RF
LUK
CBOE
BRK.B
NAVI
LNC
PFG
KEY
BBT
L
JPM
MTB
AIG
AJG
TROW
TRV
ETFC
C
ICE
AON
PBCT
MMC
MS
CFG
MCO
CB
HBAN
AMG
BK
SCHW
CMA
AFL
SPGI
SIVB
DFS
IVZ
STT
CINF
TMK
STI
SYF
MET
CME
RE
USB
SECTEUR  3
ISRG
BIIB
ILMN
HUM
ANTM
BMY
IDXX
NKTR
MRK
COO
INCY
XRAY
MYL
BDX
HOLX
MTD
LLY
ABT
DHR
DVA
TMO
AET
ABBV
BSX
IQV
MCK
LH
MDT
CAH
PRGO
DGX
CERN
REGN
RMD
ESRX
CI
HSIC
BAX
EW
JNJ
AGN
A
ALGN
ALXN
EVHC
HCA
CNC
PKI
PFE
ABC
GILD
AMGN
SYK
CELG
SECTEUR  4
ARNC
COL
DAL
AYI
TDG
ROP
ALK
AOS
RTN
LMT
FTV
RSG
SRCL
PNR
MMM
LLL
AAL
MAS
NSC
ROK
PCAR
NOC
PH
PWR
RHI
AME
NLSN
TXT
CHRW
ALLE
DE
LUV
DOV
ITW
CAT
FBHS
IR
ETN
HON
GD
GE
FLS
HII
JBHT
FDX
CTAS
FLR
FAST
EMR
GWW
EXPD
JCI
EFX
BA
CSX
KSU
JEC
INFO
CMI
SECTEUR  5
INTU
GOOG
SNPS
SYMC
RHT
AKAM
FB
ORCL
STX
DXC
PAYX
AMAT
QCOM
GPN
TTWO
FIS
ADS
GOOGL
IBM
EA
CRM
FISV
QRVO
FLIR
PYPL
IT
SWKS
EBAY
HRS
FFIV
NVDA
LRCX
INTC
NFLX
MSI
NTAP
ADBE
ANSS
MA
TSS
ADSK
ATVI
TXN
CSRA
GLW
KLAC
IPGP
CTSH
JNPR
ADP
ACN
CDNS
HPE
MSFT
CSCO
AVGO
HPQ
MCHP
MU
TEL
AAPL
CTXS
APH
AMD
ADI
CA
SECTEUR  6
PPG
PX
APD
MOS
CF
SHW
DWDP
MON
SEE
ALB
FCX
AVY
FMC
PKG
LYB
EMN
IFF
MLM
NUE
BLL
NEM
IP
ECL
SECTEUR  7
DLR
MAA
O
CBRE
AMT
MAC
BXP
KIM
DRE
IRM
EQR
HCP
CCI
UDR
SLG
HST
EXR
AVB
SBAC
REG
PSA
ESS
AIV
SPG
GGP
EQIX
ARE
PLD
FRT
SECTEUR  8
CTL
T
SECTEUR  9
RCL
GPS
UAA
HLT
HD
IPG
BWA
BKNG
KSS
BBY
LB
LKQ
LOW
AZO
MAR
MAT
MCD
LEG
APTV
HBI
HOG
KMX
HAS
CMCSA
DHI
DRI
DISCA
CMG
KORS
DISCK
DISH
DG
DLTR
LEN
FL
F
ORLY
MGM
CBS
GM
GPC
GT
CCL
M
PHM
TRIP
FOX
TSCO
SNA
SWK
SBUX
ROST
GRMN
CHTR
TPR
OMC
MHK
TGT
TJX
PVH
EXPE
NWL
RL
NKE
NWS
NCLH
AAP
JWN
NWSA
DIS
TIF
AMZN
FOXA
ULTA
TWX
NI
EIX
PEG
EXC
ES
PCG
CNP
SCG
CMS
ED
FE
AES
SRE
ETR
NEE
PNW
DTE
AEP
SO
D
AEE
DUK
PPL
LNT
NRG
AWK

In [36]:
name

[123]