In [30]:
___Author___='LumberJack Jyss'

In [31]:
from jupyterthemes import jtplot
jtplot.style(theme='onedork')
jtplot.style(context='talk', fscale=1.4, spines=False, gridlines='--')
jtplot.style(ticks=True, grid=True, figsize=(16, 6))
# jtplot.reset()

In [32]:
import numpy as np
import pandas as pd
import scipy
import statsmodels.api as sm
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras import layers
import seaborn as sns
sns.set_context("paper")
sns.set_palette("husl")
sns.set(palette='bright',style='whitegrid') #["deep", "muted", "pastel", "bright", "dark", "colorblind"]
print('Version TensorFlow : ',tf.VERSION)
print(tf.keras.__version__)

Version TensorFlow :  1.12.0
2.1.6-tf

In [33]:
%matplotlib inline

In [34]:
raw_data=pd.read_csv('data.csv')
df=raw_data.copy()
df=df[['Date','Close_GSPC']]
df=df.drop([1258],axis=0)
df.head()

         Date   Close_GSPC
0  2014-03-10  1867.630005
1  2014-03-11  1868.199951
2  2014-03-12  1846.339966
3  2014-03-13  1841.130005
4  2014-03-14  1858.829956

In [35]:
df['Date']=pd.to_datetime(df['Date'])
df.set_index('Date',inplace=True)
df.head()

             Close_GSPC
Date
2014-03-10  1867.630005
2014-03-11  1868.199951
2014-03-12  1846.339966
2014-03-13  1841.130005
2014-03-14  1858.829956

In [36]:
df.tail()

             Close_GSPC
Date
2019-03-01  2792.810059
2019-03-04  2789.649902
2019-03-05  2771.449951
2019-03-06  2748.929932
2019-03-07  2743.070068

In [37]:
from statsmodels.tsa.seasonal import seasonal_decompose

In [38]:
time_series=df['Close_GSPC'].dropna()
type(time_series)

pandas.core.series.Series

In [39]:
from statsmodels.tsa.seasonal import seasonal_decompose

In [40]:
decomp=seasonal_decompose(time_series,freq=150)

In [41]:
 from statsmodels.tsa.stattools import adfuller

In [42]:
result = adfuller(df['Close_GSPC'].dropna())

In [43]:
def adf_check (time_series):
    result=adfuller(time_series)
    print('Augmented Dicky-Fuller Test : ')
    labels=['ADF Test Statistic', 'p-value','# of lags','# of observations used']
    for value,label in zip(result,labels):
        print(label+' : '+str(value))
    if result[1] <= 0.05:
        print ('Strong evidence again null hypothesis')
        print('Reject null hypothesis')
        print ('Data has no unit root and is **stationary**')
    else:
        print ('Weak evidence again null hypothesis')
        print('Failed to reject null hypothesis')
        print ('Data has a unit root and is ** non-stationary**')

In [44]:
adf_check(df['Close_GSPC'].dropna())

Augmented Dicky-Fuller Test :
ADF Test Statistic : -0.7584682144830559
p-value : 0.8310184410171679
# of lags : 17
# of observations used : 1240
Weak evidence again null hypothesis
Failed to reject null hypothesis
Data has a unit root and is ** non-stationary**

In [45]:
df['First Difference']=df['Close_GSPC']-df['Close_GSPC'].shift(1)

In [46]:
 adf_check(df['First Difference'].dropna())

Augmented Dicky-Fuller Test :
ADF Test Statistic : -9.164835198279329
p-value : 2.4767596935467522e-15
# of lags : 16
# of observations used : 1240
Strong evidence again null hypothesis
Reject null hypothesis
Data has no unit root and is **stationary**

In [47]:
df['Second Difference']=df['First Difference']-df['First Difference'].shift(1)

In [48]:
 adf_check(df['Second Difference'].dropna())

Augmented Dicky-Fuller Test :
ADF Test Statistic : -13.997215402575007
p-value : 3.919999434589675e-26
# of lags : 21
# of observations used : 1234
Strong evidence again null hypothesis
Reject null hypothesis
Data has no unit root and is **stationary**

In [49]:
df['Seasonal Difference']=df['Close_GSPC']-df['Close_GSPC'].shift(150)

In [50]:
 adf_check(df['Seasonal Difference'].dropna())

Augmented Dicky-Fuller Test :
ADF Test Statistic : -2.7169400000048682
p-value : 0.07115250151554853
# of lags : 21
# of observations used : 1086
Weak evidence again null hypothesis
Failed to reject null hypothesis
Data has a unit root and is ** non-stationary**

In [51]:
df['Seasonal First Difference']=df['First Difference']-df['First Difference'].shift(1)

In [52]:
adf_check(df['Seasonal First Difference'].dropna())

Augmented Dicky-Fuller Test :
ADF Test Statistic : -13.997215402575007
p-value : 3.919999434589675e-26
# of lags : 21
# of observations used : 1234
Strong evidence again null hypothesis
Reject null hypothesis
Data has no unit root and is **stationary**

In [53]:
#from statsmodels.graphics.tsaplots import plot_acf,plot_pacf

In [54]:
from statsmodels.tsa.arima_model import ARIMA

In [55]:
 help(ARIMA)

Help on class ARIMA in module statsmodels.tsa.arima_model:

class ARIMA(ARMA)
 |  Autoregressive Integrated Moving Average ARIMA(p,d,q) Model
 |
 |  Parameters
 |  ----------
 |  endog : array-like
 |      The endogenous variable.
 |  order : iterable
 |      The (p,d,q) order of the model for the number of AR parameters,
 |      differences, and MA parameters to use.
 |  exog : array-like, optional
 |      An optional array of exogenous variables. This should *not* include a
 |      constant or trend. You can specify this in the `fit` method.
 |  dates : array-like of datetime, optional
 |      An array-like object of datetime objects. If a pandas object is given
 |      for endog or exog, it is assumed to have a DateIndex.
 |  freq : str, optional
 |      The frequency of the time-series. A Pandas offset or 'B', 'D', 'W',
 |      'M', 'A', or 'Q'. This is optional if dates are given.
 |
 |
 |  Notes
 |  -----
 |  If exogenous variables are given, then the model that is fit is
 |
 |  .. math::
 |
 |     \phi(L)(y_t - X_t\beta) = \theta(L)\epsilon_t
 |
 |  where :math:`\phi` and :math:`\theta` are polynomials in the lag
 |  operator, :math:`L`. This is the regression model with ARMA errors,
 |  or ARMAX model. This specification is used, whether or not the model
 |  is fit using conditional sum of square or maximum-likelihood, using
 |  the `method` argument in
 |  :meth:`statsmodels.tsa.arima_model.ARIMA.fit`. Therefore, for
 |  now, `css` and `mle` refer to estimation methods only. This may
 |  change for the case of the `css` model in future versions.
 |
 |  Method resolution order:
 |      ARIMA
 |      ARMA
 |      statsmodels.tsa.base.tsa_model.TimeSeriesModel
 |      statsmodels.base.model.LikelihoodModel
 |      statsmodels.base.model.Model
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __getnewargs__(self)
 |
 |  __init__(self, endog, order, exog=None, dates=None, freq=None, missing='none')
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  fit(self, start_params=None, trend='c', method='css-mle', transparams=True, solver='lbfgs', maxiter=500, full_output=1, disp=5, callback=None, start_ar_lags=None, **kwargs)
 |      Fits ARIMA(p,d,q) model by exact maximum likelihood via Kalman filter.
 |
 |      Parameters
 |      ----------
 |      start_params : array-like, optional
 |          Starting parameters for ARMA(p,q).  If None, the default is given
 |          by ARMA._fit_start_params.  See there for more information.
 |      transparams : bool, optional
 |          Whehter or not to transform the parameters to ensure stationarity.
 |          Uses the transformation suggested in Jones (1980).  If False,
 |          no checking for stationarity or invertibility is done.
 |      method : str {'css-mle','mle','css'}
 |          This is the loglikelihood to maximize.  If "css-mle", the
 |          conditional sum of squares likelihood is maximized and its values
 |          are used as starting values for the computation of the exact
 |          likelihood via the Kalman filter.  If "mle", the exact likelihood
 |          is maximized via the Kalman Filter.  If "css" the conditional sum
 |          of squares likelihood is maximized.  All three methods use
 |          `start_params` as starting parameters.  See above for more
 |          information.
 |      trend : str {'c','nc'}
 |          Whether to include a constant or not.  'c' includes constant,
 |          'nc' no constant.
 |      solver : str or None, optional
 |          Solver to be used.  The default is 'lbfgs' (limited memory
 |          Broyden-Fletcher-Goldfarb-Shanno).  Other choices are 'bfgs',
 |          'newton' (Newton-Raphson), 'nm' (Nelder-Mead), 'cg' -
 |          (conjugate gradient), 'ncg' (non-conjugate gradient), and
 |          'powell'. By default, the limited memory BFGS uses m=12 to
 |          approximate the Hessian, projected gradient tolerance of 1e-8 and
 |          factr = 1e2. You can change these by using kwargs.
 |      maxiter : int, optional
 |          The maximum number of function evaluations. Default is 500.
 |      tol : float
 |          The convergence tolerance.  Default is 1e-08.
 |      full_output : bool, optional
 |          If True, all output from solver will be available in
 |          the Results object's mle_retvals attribute.  Output is dependent
 |          on the solver.  See Notes for more information.
 |      disp : int, optional
 |          If True, convergence information is printed.  For the default
 |          l_bfgs_b solver, disp controls the frequency of the output during
 |          the iterations. disp < 0 means no output in this case.
 |      callback : function, optional
 |          Called after each iteration as callback(xk) where xk is the current
 |          parameter vector.
 |      start_ar_lags : int, optional
 |          Parameter for fitting start_params. When fitting start_params,
 |          residuals are obtained from an AR fit, then an ARMA(p,q) model is
 |          fit via OLS using these residuals. If start_ar_lags is None, fit
 |          an AR process according to best BIC. If start_ar_lags is not None,
 |          fits an AR process with a lag length equal to start_ar_lags.
 |          See ARMA._fit_start_params_hr for more information.
 |      kwargs
 |          See Notes for keyword arguments that can be passed to fit.
 |
 |      Returns
 |      -------
 |      `statsmodels.tsa.arima.ARIMAResults` class
 |
 |      See also
 |      --------
 |      statsmodels.base.model.LikelihoodModel.fit : for more information
 |          on using the solvers.
 |      ARIMAResults : results class returned by fit
 |
 |      Notes
 |      ------
 |      If fit by 'mle', it is assumed for the Kalman Filter that the initial
 |      unkown state is zero, and that the inital variance is
 |      P = dot(inv(identity(m**2)-kron(T,T)),dot(R,R.T).ravel('F')).reshape(r,
 |      r, order = 'F')
 |
 |  predict(self, params, start=None, end=None, exog=None, typ='linear', dynamic=False)
 |      ARIMA model in-sample and out-of-sample prediction
 |
 |      Parameters
 |      ----------
 |      params : array-like
 |          The fitted parameters of the model.
 |      start : int, str, or datetime
 |          Zero-indexed observation number at which to start forecasting, ie.,
 |          the first forecast is start. Can also be a date string to
 |          parse or a datetime type.
 |      end : int, str, or datetime
 |          Zero-indexed observation number at which to end forecasting, ie.,
 |          the first forecast is start. Can also be a date string to
 |          parse or a datetime type. However, if the dates index does not
 |          have a fixed frequency, end must be an integer index if you
 |          want out of sample prediction.
 |      exog : array-like, optional
 |          If the model is an ARMAX and out-of-sample forecasting is
 |          requested, exog must be given. Note that you'll need to pass
 |          `k_ar` additional lags for any exogenous variables. E.g., if you
 |          fit an ARMAX(2, q) model and want to predict 5 steps, you need 7
 |          observations to do this.
 |      dynamic : bool, optional
 |          The `dynamic` keyword affects in-sample prediction. If dynamic
 |          is False, then the in-sample lagged values are used for
 |          prediction. If `dynamic` is True, then in-sample forecasts are
 |          used in place of lagged dependent variables. The first forecasted
 |          value is `start`.
 |      typ : str {'linear', 'levels'}
 |
 |          - 'linear' : Linear prediction in terms of the differenced
 |            endogenous variables.
 |          - 'levels' : Predict the levels of the original endogenous
 |            variables.
 |
 |
 |      Returns
 |      -------
 |      predict : array
 |          The predicted values.
 |
 |
 |
 |      Notes
 |      -----
 |      Use the results predict method instead.
 |
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |
 |  __new__(cls, endog, order, exog=None, dates=None, freq=None, missing='none')
 |      Create and return a new object.  See help(type) for accurate signature.
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from ARMA:
 |
 |  geterrors(self, params)
 |      Get the errors of the ARMA process.
 |
 |      Parameters
 |      ----------
 |      params : array-like
 |          The fitted ARMA parameters
 |      order : array-like
 |          3 item iterable, with the number of AR, MA, and exogenous
 |          parameters, including the trend
 |
 |  hessian(self, params)
 |      Compute the Hessian at params,
 |
 |      Notes
 |      -----
 |      This is a numerical approximation.
 |
 |  loglike(self, params, set_sigma2=True)
 |      Compute the log-likelihood for ARMA(p,q) model
 |
 |      Notes
 |      -----
 |      Likelihood used depends on the method set in fit
 |
 |  loglike_css(self, params, set_sigma2=True)
 |      Conditional Sum of Squares likelihood function.
 |
 |  loglike_kalman(self, params, set_sigma2=True)
 |      Compute exact loglikelihood for ARMA(p,q) model by the Kalman Filter.
 |
 |  score(self, params)
 |      Compute the score function at params.
 |
 |      Notes
 |      -----
 |      This is a numerical approximation.
 |
 |  ----------------------------------------------------------------------
 |  Class methods inherited from ARMA:
 |
 |  from_formula(formula, data, subset=None, drop_cols=None, *args, **kwargs) from builtins.type
 |      Create a Model from a formula and dataframe.
 |
 |      Parameters
 |      ----------
 |      formula : str or generic Formula object
 |          The formula specifying the model
 |      data : array-like
 |          The data for the model. See Notes.
 |      subset : array-like
 |          An array-like object of booleans, integers, or index values that
 |          indicate the subset of df to use in the model. Assumes df is a
 |          `pandas.DataFrame`
 |      drop_cols : array-like
 |          Columns to drop from the design matrix.  Cannot be used to
 |          drop terms involving categoricals.
 |      args : extra arguments
 |          These are passed to the model
 |      kwargs : extra keyword arguments
 |          These are passed to the model with one exception. The
 |          ``eval_env`` keyword is passed to patsy. It can be either a
 |          :class:`patsy:patsy.EvalEnvironment` object or an integer
 |          indicating the depth of the namespace to use. For example, the
 |          default ``eval_env=0`` uses the calling namespace. If you wish
 |          to use a "clean" environment set ``eval_env=-1``.
 |
 |      Returns
 |      -------
 |      model : Model instance
 |
 |      Notes
 |      ------
 |      data must define __getitem__ with the keys in the formula terms
 |      args and kwargs are passed on to the model instantiation. E.g.,
 |      a numpy structured or rec array, a dictionary, or a pandas DataFrame.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from statsmodels.tsa.base.tsa_model.TimeSeriesModel:
 |
 |  exog_names
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from statsmodels.base.model.LikelihoodModel:
 |
 |  information(self, params)
 |      Fisher information matrix of model
 |
 |      Returns -Hessian of loglike evaluated at params.
 |
 |  initialize(self)
 |      Initialize (possibly re-initialize) a Model instance. For
 |      instance, the design matrix of a linear model may change
 |      and some things must be recomputed.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from statsmodels.base.model.Model:
 |
 |  __dict__
 |      dictionary for instance variables (if defined)
 |
 |  __weakref__
 |      list of weak references to the object (if defined)
 |
 |  endog_names
 |      Names of endogenous variables

In [57]:
model = sm.tsa.statespace.SARIMAX(df['Close_GSPC'],order=(0,1,0),seasonal_order=(1,1,1,150))

/Users/YTsBaCh/Applications/anaconda3/lib/python3.6/site-packages/statsmodels/tsa/base/tsa_model.py:225: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)

In [58]:
result = model.fit()

In [60]:
print(result.summary())

                                  Statespace Model Results
===========================================================================================
Dep. Variable:                          Close_GSPC   No. Observations:                 1258
Model:             SARIMAX(0, 1, 0)x(1, 1, 1, 150)   Log Likelihood               -4993.661
Date:                             Thu, 14 Mar 2019   AIC                           9993.321
Time:                                     17:16:59   BIC                          10008.350
Sample:                                          0   HQIC                          9999.005
                                            - 1258
Covariance Type:                               opg
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
ar.S.L150     -0.0653      0.057     -1.149      0.251      -0.177       0.046
ma.S.L150     -0.7477      0.068    -10.945      0.000      -0.882      -0.614
sigma2       428.7887     12.891     33.263      0.000     403.523     454.054
===================================================================================
Ljung-Box (Q):                       67.79   Jarque-Bera (JB):               688.97
Prob(Q):                              0.00   Prob(JB):                         0.00
Heteroskedasticity (H):               1.90   Skew:                            -0.36
Prob(H) (two-sided):                  0.00   Kurtosis:                         6.80
===================================================================================

Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step).

In [76]:
# Let's get predict
df['Forecast']=result.predict(start=1,end=1000)

In [85]:
df=df.iloc[1:,:]
df.head()

,Close_GSPC,First Difference,Second Difference,Seasonal Difference,Seasonal First Difference,Forecast
Date,,,,,,
2014-03-12,1846.339966,-21.859985,-22.429931,NaN,-22.429931,1868.199951
2014-03-13,1841.130005,-5.209961,16.650024,NaN,16.650024,1846.339966
2014-03-14,1858.829956,17.699951,22.909912,NaN,22.909912,1841.130005
2014-03-17,1872.250000,13.420044,-4.279907,NaN,-4.279907,1858.829956
2014-03-18,1860.770020,-11.479980,-24.900024,NaN,-24.900024,1872.250000

In [92]:
df.tail(258)

,Close_GSPC,First Difference,Second Difference,Seasonal Difference,Seasonal First Difference,Forecast
Date,,,,,,
2018-02-27,2713.830078,-30.449951,4.870118,236.700195,4.870118,2749.124438
2018-02-28,2677.669922,-36.160156,-5.710205,199.839844,-5.710205,NaN
2018-03-01,2691.250000,13.580078,49.740234,215.830078,49.740234,NaN
2018-03-02,2720.939941,29.689941,16.109863,248.839843,16.109863,NaN
2018-03-05,2728.120117,7.180176,-22.509765,257.820068,-22.509765,NaN
2018-03-06,2726.800049,-1.320068,-8.500244,250.449951,-8.500244,NaN
2018-03-07,2738.969971,12.169922,13.489990,261.399903,13.489990,NaN
2018-03-08,2786.570068,47.600097,35.430175,314.410156,35.430175,NaN
2018-03-09,2783.020020,-3.550048,-51.150145,306.189942,-51.150145,NaN
2018-03-12,2765.310059,-17.709961,-14.159913,284.400147,-14.159913,NaN
2018-03-13,2749.479980,-15.830079,1.879882,274.560058,1.879882,NaN
2018-03-14,2747.330078,-2.149902,13.680177,273.310058,13.680177,NaN
2018-03-15,2752.010010,4.679932,6.829834,313.800049,6.829834,NaN
2018-03-16,2712.919922,-39.090088,-43.770020,271.599854,-43.770020,NaN
2018-03-19,2716.939941,4.020019,43.110107,251.099853,43.110107,NaN
2018-03-20,2711.929932,-5.010009,-9.030028,247.319825,-9.030028,NaN
2018-03-21,2643.689941,-68.239991,-63.229982,175.579834,-63.229982,NaN
2018-03-22,2588.260010,-55.429931,12.810060,158.250000,12.810060,NaN
2018-03-23,2658.550049,70.290039,125.719970,233.000000,125.719970,NaN
2018-03-26,2612.620117,-45.929932,-116.219971,184.250000,-116.219971,NaN
2018-03-27,2605.000000,-7.620117,38.309815,152.489990,38.309815,NaN
2018-03-28,2640.870117,35.870117,43.490234,196.830078,43.490234,NaN
2018-03-29,2581.879883,-58.990234,-94.860351,142.909912,-94.860351,NaN
2018-04-02,2614.449951,32.570068,91.560302,171.399902,91.560302,NaN
2018-04-03,2644.689941,30.239990,-2.330078,200.449951,-2.330078,NaN
2018-04-04,2662.840088,18.150147,-12.089843,216.540039,-12.089843,NaN
2018-04-05,2604.469971,-58.370117,-76.520264,146.879883,-76.520264,NaN
2018-04-06,2613.159912,8.689941,67.060058,141.510010,67.060058,NaN
2018-04-09,2656.870117,43.710205,35.020264,180.320068,35.020264,NaN
2018-04-10,2642.189941,-14.680176,-58.390381,184.339843,-58.390381,NaN
...,...,...,...,...,...,...
2019-01-24,2664.760010,22.429932,18.799805,-102.560058,18.799805,NaN
2019-01-25,2643.850098,-20.909912,-43.339844,-105.909912,-43.339844,NaN
2019-01-28,2640.000000,-3.850098,17.059814,-114.879883,17.059814,NaN
2019-01-29,2681.050049,41.050049,44.900147,-36.020019,44.900147,NaN
2019-01-30,2704.100098,23.050049,-18.000000,-18.959961,-18.000000,NaN
2019-01-31,2706.530029,2.429931,-20.620118,6.900146,-20.620118,NaN
2019-02-01,2724.870117,18.340088,15.910157,8.560058,15.910157,NaN
2019-02-04,2737.699951,12.829834,-5.510254,19.329834,-5.510254,NaN
2019-02-05,2731.610107,-6.089844,-18.919678,4.900146,-18.919678,NaN
2019-02-06,2706.050049,-25.560058,-19.470214,-7.169922,-19.470214,NaN
2019-02-07,2707.879883,1.829834,27.389892,-28.730224,27.389892,NaN
2019-02-08,2709.800049,1.920166,0.090332,-50.020019,0.090332,NaN
2019-02-11,2744.729980,34.929931,33.009765,-39.439942,33.009765,NaN
2019-02-12,2753.030029,8.300049,-26.629882,-40.810059,-26.629882,NaN
2019-02-13,2745.729980,-7.300049,-15.600098,-28.290040,-15.600098,NaN
2019-02-14,2775.600098,29.870118,37.170167,-22.689941,37.170167,NaN
2019-02-15,2779.760010,4.159912,-25.710206,-21.550049,-25.710206,NaN
2019-02-19,2784.699951,4.939941,0.780029,-13.729981,0.780029,NaN
2019-02-20,2774.879883,-9.820068,-14.760009,-34.670166,-14.760009,NaN
2019-02-21,2792.669922,17.790039,27.610107,-22.950195,27.610107,NaN
2019-02-22,2796.110107,3.440185,-14.349854,-8.379883,-14.349854,NaN
2019-02-25,2793.899902,-2.210205,-5.650390,-7.930176,-5.650390,NaN
2019-02-26,2792.379883,-1.520019,0.690186,-14.600097,0.690186,NaN
2019-02-27,2784.489990,-7.889893,-6.369874,-35.909912,-6.369874,NaN
2019-02-28,2803.689941,19.199951,27.089844,-42.380127,27.089844,NaN
2019-03-01,2792.810059,-10.879882,-30.079833,-44.629882,-30.079833,NaN
2019-03-04,2789.649902,-3.160157,7.719725,-29.170166,7.719725,NaN
2019-03-05,2771.449951,-18.199951,-15.039794,-31.150147,-15.039794,NaN
2019-03-06,2748.929932,-22.520019,-4.320068,-67.360107,-4.320068,NaN
2019-03-07,2743.070068,-5.859864,16.660155,-70.290039,16.660155,NaN

In [93]:
#Essayons sur la fin
df['Forecast']=result.predict(start=1001,end=1257)
df.tail()

,Close_GSPC,First Difference,Second Difference,Seasonal Difference,Seasonal First Difference,Forecast
Date,,,,,,
2019-03-01,2792.810059,-10.879882,-30.079833,-44.629882,-30.079833,2791.191130
2019-03-04,2789.649902,-3.160157,7.719725,-29.170166,7.719725,2790.169678
2019-03-05,2771.449951,-18.199951,-15.039794,-31.150147,-15.039794,2790.433922
2019-03-06,2748.929932,-22.520019,-4.320068,-67.360107,-4.320068,2775.303204
2019-03-07,2743.070068,-5.859864,16.660155,-70.290039,16.660155,2746.913816

In [94]:
from pandas.tseries.offsets import DateOffset

In [95]:
future_date=[df.index[-1] + DateOffset(days=x)for x in range(0,14)]

In [96]:
future_date

[Timestamp('2019-03-07 00:00:00'),
 Timestamp('2019-03-08 00:00:00'),
 Timestamp('2019-03-09 00:00:00'),
 Timestamp('2019-03-10 00:00:00'),
 Timestamp('2019-03-11 00:00:00'),
 Timestamp('2019-03-12 00:00:00'),
 Timestamp('2019-03-13 00:00:00'),
 Timestamp('2019-03-14 00:00:00'),
 Timestamp('2019-03-15 00:00:00'),
 Timestamp('2019-03-16 00:00:00'),
 Timestamp('2019-03-17 00:00:00'),
 Timestamp('2019-03-18 00:00:00'),
 Timestamp('2019-03-19 00:00:00'),
 Timestamp('2019-03-20 00:00:00')]

In [115]:
future_df=pd.DataFrame(index=future_date,columns=df.columns)
future_df

,Close_GSPC,First Difference,Second Difference,Seasonal Difference,Seasonal First Difference,Forecast
2019-03-07,NaN,NaN,NaN,NaN,NaN,NaN
2019-03-08,NaN,NaN,NaN,NaN,NaN,NaN
2019-03-09,NaN,NaN,NaN,NaN,NaN,NaN
2019-03-10,NaN,NaN,NaN,NaN,NaN,NaN
2019-03-11,NaN,NaN,NaN,NaN,NaN,NaN
2019-03-12,NaN,NaN,NaN,NaN,NaN,NaN
2019-03-13,NaN,NaN,NaN,NaN,NaN,NaN
2019-03-14,NaN,NaN,NaN,NaN,NaN,NaN
2019-03-15,NaN,NaN,NaN,NaN,NaN,NaN
2019-03-16,NaN,NaN,NaN,NaN,NaN,NaN
2019-03-17,NaN,NaN,NaN,NaN,NaN,NaN
2019-03-18,NaN,NaN,NaN,NaN,NaN,NaN
2019-03-19,NaN,NaN,NaN,NaN,NaN,NaN
2019-03-20,NaN,NaN,NaN,NaN,NaN,NaN

In [117]:
final_df=pd.concat([df,future_df])
#final_df['Forecast']=result.predict(start=1261,end=1270)
final_df.tail(15)

,Close_GSPC,First Difference,Second Difference,Seasonal Difference,Seasonal First Difference,Forecast
2019-03-07,2743.070068,-5.859864,16.660155,-70.290039,16.660155,2746.913816
2019-03-07,NaN,NaN,NaN,NaN,NaN,NaN
2019-03-08,NaN,NaN,NaN,NaN,NaN,NaN
2019-03-09,NaN,NaN,NaN,NaN,NaN,NaN
2019-03-10,NaN,NaN,NaN,NaN,NaN,NaN
2019-03-11,NaN,NaN,NaN,NaN,NaN,NaN
2019-03-12,NaN,NaN,NaN,NaN,NaN,NaN
2019-03-13,NaN,NaN,NaN,NaN,NaN,NaN
2019-03-14,NaN,NaN,NaN,NaN,NaN,NaN
2019-03-15,NaN,NaN,NaN,NaN,NaN,NaN
2019-03-16,NaN,NaN,NaN,NaN,NaN,NaN
2019-03-17,NaN,NaN,NaN,NaN,NaN,NaN
2019-03-18,NaN,NaN,NaN,NaN,NaN,NaN
2019-03-19,NaN,NaN,NaN,NaN,NaN,NaN
2019-03-20,NaN,NaN,NaN,NaN,NaN,NaN

In [100]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1270 entries, 2014-03-12 to 2019-03-20
Data columns (total 6 columns):
Close_GSPC                   1256 non-null float64
First Difference             1256 non-null float64
Second Difference            1256 non-null float64
Seasonal Difference          1108 non-null float64
Seasonal First Difference    1256 non-null float64
Forecast                     257 non-null float64
dtypes: float64(6)
memory usage: 69.5 KB

In [119]:
result.predict(start=1258,end=1270)

/Users/YTsBaCh/Applications/anaconda3/lib/python3.6/site-packages/statsmodels/tsa/base/tsa_model.py:531: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  ValueWarning)

1258    2746.993631
1259    2756.193220
1260    2758.877774
1261    2764.842319
1262    2769.106518
1263    2770.436484
1264    2768.869737
1265    2760.824453
1266    2761.916753
1267    2752.625028
1268    2757.786118
1269    2771.735811
1270    2771.952334
dtype: float64

In [125]:
final_df['Forecast']=result.predict(start=1256,end=1270)

/Users/YTsBaCh/Applications/anaconda3/lib/python3.6/site-packages/statsmodels/tsa/base/tsa_model.py:531: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  ValueWarning)

In [129]:
final_df.tail()

,Close_GSPC,First Difference,Second Difference,Seasonal Difference,Seasonal First Difference,Forecast
2019-03-16,NaN,NaN,NaN,NaN,NaN,NaN
2019-03-17,NaN,NaN,NaN,NaN,NaN,NaN
2019-03-18,NaN,NaN,NaN,NaN,NaN,NaN
2019-03-19,NaN,NaN,NaN,NaN,NaN,NaN
2019-03-20,NaN,NaN,NaN,NaN,NaN,NaN

In [124]:
final_df.iloc[1256,:]

Close_GSPC                  NaN
First Difference            NaN
Second Difference           NaN
Seasonal Difference         NaN
Seasonal First Difference   NaN
Forecast                    NaN
Name: 2019-03-07 00:00:00, dtype: float64