In [2]:
___Author___='LumberJack Jyss'

In [3]:
print('LumberJack BRUTAL AtidotCom TREND FORECAST\nLumberJack Jyss (c)')

LumberJack BRUTAL AtidotCom TREND FORECAST
LumberJack Jyss (c)

In [4]:
import pandas as pd
import numpy as np
import talib

In [5]:
df =  pd.read_csv('dataset_60.csv')

FileNotFoundError: [Errno 2] File b'dataset_60.csv' does not exist: b'dataset_60.csv'

In [ ]:
df.head()

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131784 entries, 0 to 131783
Data columns (total 36 columns):
Local time       131784 non-null object
Open_audusd      131784 non-null float64
High_audusd      131784 non-null float64
Low_audusd       131784 non-null float64
Close_audusd     131784 non-null float64
Volume_audusd    131784 non-null float64
Open_usdjpy      131784 non-null float64
High_usdjpy      131784 non-null float64
Low_usdjpy       131784 non-null float64
Close_usdjpy     131784 non-null float64
Volume_usdjpy    131784 non-null float64
Open_gbpusd      131784 non-null float64
High_gbpusd      131784 non-null float64
Low_gbpusd       131784 non-null float64
Close_gbpusd     131784 non-null float64
Volume_gbpusd    131784 non-null float64
Open_nzdusd      131784 non-null float64
High_nzdusd      131784 non-null float64
Low_nzdusd       131784 non-null float64
Close_nzdusd     131784 non-null float64
Volume_nzdusd    131784 non-null float64
Open_usdcad      131784 non-null float64
High_usdcad      131784 non-null float64
Low_usdcad       131784 non-null float64
Close_usdcad     131784 non-null float64
Volume_usdcad    131784 non-null float64
Open_usdchf      131784 non-null float64
High_usdchf      131784 non-null float64
Low_usdchf       131784 non-null float64
Close_usdchf     131784 non-null float64
Volume_usdchf    131784 non-null float64
Open_eurusd      131784 non-null float64
High_eurusd      131784 non-null float64
Low_eurusd       131784 non-null float64
Close_eurusd     131784 non-null float64
Volume_eurusd    131784 non-null float64
dtypes: float64(35), object(1)
memory usage: 36.2+ MB

In [7]:
macd, macdsignal, macdhist = talib.MACD(df['Close_eurusd'], fastperiod=50, slowperiod=200, signalperiod=20)

In [8]:
rsi = talib.RSI(df['Close_eurusd'], timeperiod=5)

In [9]:
upperband, middleband, lowerband = talib.BBANDS(df['Close_eurusd'], timeperiod=20, nbdevup=2, nbdevdn=2, matype=0)

In [10]:
atr = talib.ATR(df['High_eurusd'], df['Low_eurusd'], df['Close_eurusd'], timeperiod=14)

In [11]:
wclprice = talib.WCLPRICE(df['High_eurusd'], df['Low_eurusd'], df['Close_eurusd'])

In [12]:
df['Macdsignal_eurusd'] = macdsignal
df['rsi_eurusd'] = rsi
df['BBup_eurusd'] = upperband
df['BBmid_eurusd'] = middleband
df['BBlow_eurusd'] = lowerband
df['atr_eurusd'] = atr
df['wclprince_eurusd'] = wclprice
df.head()

,Local time,Open_audusd,High_audusd,Low_audusd,Close_audusd,Volume_audusd,Open_usdjpy,High_usdjpy,Low_usdjpy,Close_usdjpy,...,Low_eurusd,Close_eurusd,Volume_eurusd,Macdsignal_eurusd,rsi_eurusd,BBup_eurusd,BBmid_eurusd,BBlow_eurusd,atr_eurusd,wclprince_eurusd
0,01.04.2004 00:00:00.000 GMT+0200,0.76641,0.76710,0.76488,0.76535,62950.6680,104.201,104.296,104.120,104.240,...,1.23043,1.23078,25020.6992,NaN,NaN,NaN,NaN,NaN,NaN,1.230970
1,01.04.2004 01:00:00.000 GMT+0200,0.76529,0.76595,0.76420,0.76563,111419.3047,104.227,104.341,103.966,104.010,...,1.22995,1.23026,27288.0996,NaN,NaN,NaN,NaN,NaN,NaN,1.230380
2,01.04.2004 02:00:00.000 GMT+0200,0.76531,0.76559,0.76369,0.76419,55551.5820,104.007,104.176,103.806,104.172,...,1.22736,1.22763,26442.9004,NaN,NaN,NaN,NaN,NaN,NaN,1.228293
3,01.04.2004 03:00:00.000 GMT+0200,0.76410,0.76448,0.76240,0.76273,53136.6680,104.167,104.413,104.158,104.264,...,1.22645,1.22683,26449.3008,NaN,NaN,NaN,NaN,NaN,NaN,1.227120
4,01.04.2004 04:00:00.000 GMT+0200,0.76273,0.76334,0.76102,0.76153,78062.3906,104.262,104.464,104.234,104.365,...,1.22642,1.22698,28437.3008,NaN,NaN,NaN,NaN,NaN,NaN,1.227123

In [13]:
df = df.dropna()
df.shape

(131566, 43)

In [14]:
df.head()

,Local time,Open_audusd,High_audusd,Low_audusd,Close_audusd,Volume_audusd,Open_usdjpy,High_usdjpy,Low_usdjpy,Close_usdjpy,...,Low_eurusd,Close_eurusd,Volume_eurusd,Macdsignal_eurusd,rsi_eurusd,BBup_eurusd,BBmid_eurusd,BBlow_eurusd,atr_eurusd,wclprince_eurusd
218,10.04.2004 02:00:00.000 GMT+0200,0.76255,0.76255,0.76255,0.76255,0.0,106.39,106.39,106.39,106.39,...,1.20888,1.20888,0.0,-0.003009,37.355005,1.210666,1.209442,1.208217,0.001222,1.20888
219,10.04.2004 03:00:00.000 GMT+0200,0.76255,0.76255,0.76255,0.76255,0.0,106.39,106.39,106.39,106.39,...,1.20888,1.20888,0.0,-0.003035,37.355005,1.210610,1.209471,1.208331,0.001134,1.20888
220,10.04.2004 04:00:00.000 GMT+0200,0.76255,0.76255,0.76255,0.76255,0.0,106.39,106.39,106.39,106.39,...,1.20888,1.20888,0.0,-0.003060,37.355005,1.210553,1.209414,1.208275,0.001053,1.20888
221,10.04.2004 05:00:00.000 GMT+0200,0.76255,0.76255,0.76255,0.76255,0.0,106.39,106.39,106.39,106.39,...,1.20888,1.20888,0.0,-0.003084,37.355005,1.210526,1.209373,1.208219,0.000978,1.20888
222,10.04.2004 06:00:00.000 GMT+0200,0.76255,0.76255,0.76255,0.76255,0.0,106.39,106.39,106.39,106.39,...,1.20888,1.20888,0.0,-0.003107,37.355005,1.210429,1.209311,1.208192,0.000908,1.20888

In [1]:
df.tail()

NameError: name 'df' is not defined

Close_eurusd = df.iloc[:,34]
Close_eurusd.head()

df = df.drop(['Close_eurusd'],axis=1)
df.head()

df['Close_eurusd'] = Close_eurusd
df = df.iloc[381:,:]

In [15]:
df = df.set_index('Local time')
df.head()

,Open_audusd,High_audusd,Low_audusd,Close_audusd,Volume_audusd,Open_usdjpy,High_usdjpy,Low_usdjpy,Close_usdjpy,Volume_usdjpy,...,Low_eurusd,Close_eurusd,Volume_eurusd,Macdsignal_eurusd,rsi_eurusd,BBup_eurusd,BBmid_eurusd,BBlow_eurusd,atr_eurusd,wclprince_eurusd
Local time,,,,,,,,,,,,,,,,,,,,,
10.04.2004 02:00:00.000 GMT+0200,0.76255,0.76255,0.76255,0.76255,0.0,106.39,106.39,106.39,106.39,0.0,...,1.20888,1.20888,0.0,-0.003009,37.355005,1.210666,1.209442,1.208217,0.001222,1.20888
10.04.2004 03:00:00.000 GMT+0200,0.76255,0.76255,0.76255,0.76255,0.0,106.39,106.39,106.39,106.39,0.0,...,1.20888,1.20888,0.0,-0.003035,37.355005,1.210610,1.209471,1.208331,0.001134,1.20888
10.04.2004 04:00:00.000 GMT+0200,0.76255,0.76255,0.76255,0.76255,0.0,106.39,106.39,106.39,106.39,0.0,...,1.20888,1.20888,0.0,-0.003060,37.355005,1.210553,1.209414,1.208275,0.001053,1.20888
10.04.2004 05:00:00.000 GMT+0200,0.76255,0.76255,0.76255,0.76255,0.0,106.39,106.39,106.39,106.39,0.0,...,1.20888,1.20888,0.0,-0.003084,37.355005,1.210526,1.209373,1.208219,0.000978,1.20888
10.04.2004 06:00:00.000 GMT+0200,0.76255,0.76255,0.76255,0.76255,0.0,106.39,106.39,106.39,106.39,0.0,...,1.20888,1.20888,0.0,-0.003107,37.355005,1.210429,1.209311,1.208192,0.000908,1.20888

In [16]:
df.to_csv('simanim.csv')

In [17]:
df.shape

(131566, 42)

ema8 = talib.EMA(spy['spy'], timeperiod=8)
ema34 = talib.EMA(spy['spy'], timeperiod=34)
spy['ema8'] = ema8
spy['ema34'] = ema34

atr14 = talib.EMA(spy['spy'], timeperiod=8)
rsi = talib.RSI(spy['spy'], timeperiod=21)
spy['atr14'] = atr14
spy['rsi'] = rsi

macd, macdsignal, macdhist = talib.MACD(spy['spy'], fastperiod=12, slowperiod=26, signalperiod=9)
spy['macd'] = macd
spy['macdsignal'] = macdsignal
spy['macdhist'] = macdhist

fastk, fastd = talib.STOCHRSI(spy['spy'], timeperiod=14, fastk_period=5, fastd_period=3, fastd_matype=0)
spy['fastk'] = fastk
spy['fastd'] = fastd

ad = talib.AD(spy['High'], spy['Low'], spy['spy'], spy['Volume'])
spy['ad'] = ad

atr = talib.ATR(spy['High'], spy['Low'], spy['spy'], timeperiod=14)
spy['atr'] = atr

wclprice = talib.WCLPRICE(spy['High'], spy['Low'], spy['spy'])
spy['wclprice'] = wclprice

sine, leadsine = talib.HT_SINE(spy['spy'])
spy['sine'] = sine
spy['leadsine'] = leadsine

upperband, middleband, lowerband = talib.BBANDS(spy['spy'], timeperiod=20, nbdevup=2, nbdevdn=2, matype=0)