In [1]:
import talib
import numpy as np
import pandas as pd
import pandas_datareader as web
from colorama import Fore, Back, Style
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import xgboost as xgb
from xgboost import XGBRegressor, plot_importance
import seaborn as sns
%matplotlib inline
plt.style.use('seaborn')
import time
import datetime as dt
import os
from sklearn.preprocessing import MinMaxScaler
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score,roc_curve,confusion_matrix,classification_report
import warnings
warnings.filterwarnings("ignore")
import tensorflow as tf

In [3]:
df = pd.DataFrame()
df['X'] = [0,1,2,3,4,5,6,7,8,9,10]
df['Y'] = [0,2,4,6,8,10,12,14,16,18,20]
df

     X   Y
0    0   0
1    1   2
2    2   4
3    3   6
4    4   8
5    5  10
6    6  12
7    7  14
8    8  16
9    9  18
10  10  20

In [4]:
X = df.copy()
X = X.drop(['Y'],axis=1)
X['Y'] = df['Y']
y = X.iloc[:,-1]
Xtrain = X.iloc[:-2,:-1]
Xtest = X.iloc[-2:-1,:-1]
yshift = y.shift(-1)
ytrain = yshift.iloc[:-2]
ytest = yshift.iloc[-2:-1]

model = xgb.XGBRegressor(n_estimators=20000, learning_rate=1, gamma=1, subsample=1, colsample_bytree=1, max_depth=100)

model.fit( Xtrain, ytrain, early_stopping_rounds=150, eval_set=[(Xtest, ytest)], verbose=0)

ytrain_pred = model.predict(Xtrain)

y_pred = model.predict(Xtest)

pred = model.predict(X.iloc[:,:-1])

df['Y.S'] = pred
df['Y.S2'] = df['Y.S']
df = df.dropna()

df

[14:11:20] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.

     X   Y        Y.S       Y.S2
0    0   0   2.328299   2.328299
1    1   2   4.140799   4.140799
2    2   4   5.265799   5.265799
3    3   6   9.439013   9.439013
4    4   8   9.439013   9.439013
5    5  10  11.308061  11.308061
6    6  12  14.504489  14.504489
7    7  14  16.346157  16.346157
8    8  16  17.228367  17.228367
9    9  18  17.228367  17.228367
10  10  20  17.228367  17.228367