In [2]:
print('Importing Librairies...')
import warnings
warnings.filterwarnings("ignore")
import ib_insync
from ib_insync import *
import numpy as np
import pandas as pd
import pandas_datareader as web
from colorama import Fore, Back, Style
import time
import datetime as dt
import os
import sys
print('Librairies imported')
print('')

___Author___='LumberJack Jyss'
print('Global Optimized LumberJack Environment Motor 55\nLumberJack Jyss 5779(c)')
print(Fore.BLUE,'°0Oo_D.A.G._26_oO0°')
print(Fore.YELLOW,Back.BLUE,'After Game IB Version v0.55',Style.RESET_ALL)

print('')
ib = IB()
compte = 'DU1507428'
def conX():
    util.startLoop()  # uncomment this line when in a notebook
    ib.connect('127.0.0.1', 7497, clientId=1)
    if ib.isConnected() == True:
        print('Golem est maintenant connecté à IB')
    return

def disconX():
    ib.disconnect()
    if ib.isConnected() == False:
        print('Golem est maintenant déconnecté de IB')
    return

def relevpoz():
    CPT = []
    QT = []
    TYPE = []
    STOCK = []
    TICK = []
    AVGCOST = []
    globalpoz = ib.positions(account=compte)
    
    if globalpoz == []:
        print("Il n'y a aucune position en cours actuellement.")
        poz = pd.DataFrame({'ALERTE': [101]}) 
    else:
        print('Il y a actuellement ',len(globalpoz),'positions en cours')
        for i in range(0,len(globalpoz)):
            CPT.append(globalpoz[i][0])
            TYPE.append(str(globalpoz[i][1]).split("(")[0])
            if str(globalpoz[i][1]).split("(")[0] == 'Future':
                TICK.append(str(globalpoz[i][1]).split("'")[1])
            elif str(globalpoz[i][1]).split("(")[0] == 'Forex':
                TICK.append(str(globalpoz[i][1]).split("'")[1])
            elif str(globalpoz[i][1]).split("(")[0] == 'Stock':
                TICK.append(str(globalpoz[i][1]).split("'")[1])
            else:
                TICK.append('NA')

            QT.append(globalpoz[i][2])
            AVGCOST.append(globalpoz[i][3])
            poz = pd.DataFrame()
            
            poz['Compte'] = CPT
            poz['Type'] = TYPE
            poz['Ticker'] = TICK
            poz['Quantité'] = QT
            poz['Average Cost'] = AVGCOST
    return(poz)
#if ib.isConnected() == False:
try:
    disconX()
except:
    conX()
time.sleep(5)
if ib.isConnected() == False:
    conX()

Importing Librairies...
Librairies imported

Global Optimized LumberJack Environment Motor 55
LumberJack Jyss 5779(c)
 °0Oo_D.A.G._26_oO0°
  After Game IB Version v0.55

Golem est maintenant déconnecté de IB
Golem est maintenant connecté à IB

In [23]:
today = str(dt.date.today())[:5]+str(dt.date.today())[5:7]+str(dt.date.today())[7:10]
startday = str(dt.date.today()-dt.timedelta(1190))[:5]+str(dt.date.today()-dt.timedelta(1190))[5:7]+str(dt.date.today()-dt.timedelta(1190))[7:10]
yesterday = str(dt.date.today()-dt.timedelta(1))[:5]+str(dt.date.today()-dt.timedelta(1))[5:7]+str(dt.date.today()-dt.timedelta(1))[7:10]
start = pd.to_datetime(startday)
end = pd.to_datetime(today)
stamp = input('Entrez la date du rapport (jour du signal. Format : YYYY-MM-DD : )')

Entrez la date du rapport (jour du signal. Format : YYYY-MM-DD : ) 2019-09-19

In [24]:
dadato = ''.join(stamp.split('-'))
dadato = str(int(dadato)+1)
dadato

'20190920'

In [25]:
try:
    signals = pd.read_csv('SIGNALS_'+stamp+'.csv')
    try:
        signals = signals.drop('Unnamed: 0',axis=1)
    except:
        pass
except:
    exit('Problème de chargement du fichier SIGNALS')

signals.tail()

,Date,Ticker,Open Long,Close Long,Open Short,Close Short,Close Price
368,19/09/19,XRAY,0,0,0,0,49.900002
369,19/09/19,XRX,0,0,0,0,30.209999
370,19/09/19,XYL,0,0,0,0,77.940002
371,19/09/19,ZBH,0,0,0,0,139.679993
372,19/09/19,ZION,0,0,0,0,44.580002

In [26]:
try:
    megasignals = pd.read_csv('MEGASIGNALS.csv')
    try:
        megasignals = megasignals.drop('Unnamed: 0',axis=1)
    except:
        pass
except:
    exit('Fichier MEGASIGNALS non présent')

megasignals.tail(1)

,Date,Ticker,Open Long,Close Long,Open Short,Close Short,Close Price
1864,24/09/19,ZION,0,0,0,0,43.77

In [27]:
if len(megasignals[megasignals['Date']=='/'.join([stamp.split('-')[2],stamp.split('-')[1],stamp.split('-')[0][2:]])]) > 2:
    print('La colonne '+'/'.join([stamp.split('-')[2],stamp.split('-')[1],stamp.split('-')[0][2:]])+' existe déjà')
else:
    print('La colonne '+'/'.join([stamp.split('-')[2],stamp.split('-')[1],stamp.split('-')[0][2:]])+' est absente')
    print('Mise à jour du fichier MEGASIGNALS')
    megasignals = pd.concat([megasignals,signals],ignore_index=True)
    try:
        megasignals = megasignals.drop('Unnamed: 0',axis=1)
    except:
        pass
    megasignals.to_csv('MEGASIGNALS.csv')
megasignals.tail()

La colonne 19/09/19 existe déjà

,Date,Ticker,Open Long,Close Long,Open Short,Close Short,Close Price
1860,24/09/19,XRAY,0,0,0,0,53.040001
1861,24/09/19,XRX,0,0,0,0,29.520000
1862,24/09/19,XYL,0,0,0,0,76.900002
1863,24/09/19,ZBH,0,0,0,0,140.089996
1864,24/09/19,ZION,0,0,0,0,43.770000

In [28]:
megatrades = pd.DataFrame()
try:
    megatrades = pd.read_csv('MEGATRADES.csv')
    try:
        megatrades = megatrades.drop('Unnamed: 0',axis=1)
        print('Fichier MEGATRADESchargé')
    except:
        print('Pas de colonne vide')
        pass
except:
    exit('Fichier MEGATRADES non présent')

megatrades.tail(1)

Pas de colonne vide

,Underlying,Action,Quantity,Price,Time,Date,Exch.,Account,Order Ref.,Clearing,Unnamed: 10
252,COG,SLD,100,18.01,15:15:11,20190923,DRCTEDGE,DU1507428,NaN,NaN,NaN

In [29]:
megatrades[megatrades['Date'] == int(''.join(stamp.split('-')))]

,Underlying,Action,Quantity,Price,Time,Date,Exch.,Account,Order Ref.,Clearing,Unnamed: 10
0,SHW,SLD,19,541.75,13:30:04,20190919,ISLAND,DU1507428,NaN,NaN,NaN
1,CTSH,SLD,20,63.38,13:30:05,20190919,ISLAND,DU1507428,NaN,NaN,NaN
2,TRV,SLD,9,146.18,13:30:05,20190919,ISLAND,DU1507428,NaN,NaN,NaN
3,PM,BOT,17,71.60,13:30:07,20190919,ISLAND,DU1507428,NaN,NaN,NaN
4,WFC,SLD,5,48.90,13:30:07,20190919,NYSENAT,DU1507428,NaN,NaN,NaN
5,WFC,SLD,100,48.90,13:30:09,20190919,BYX,DU1507428,NaN,NaN,NaN
6,WFC,SLD,100,48.90,13:30:12,20190919,BYX,DU1507428,NaN,NaN,NaN
7,MET,BOT,26,47.95,13:30:07,20190919,ISLAND,DU1507428,NaN,NaN,NaN
8,WDC,BOT,20,63.69,13:30:08,20190919,ISLAND,DU1507428,NaN,NaN,NaN
9,NTRS,BOT,13,96.07,13:30:11,20190919,ISLAND,DU1507428,NaN,NaN,NaN
10,HIG,SLD,21,60.78,13:30:11,20190919,ISLAND,DU1507428,NaN,NaN,NaN
11,NVDA,BOT,7,179.74,13:30:12,20190919,ISLAND,DU1507428,NaN,NaN,NaN
12,EOG,SLD,15,82.07,13:30:13,20190919,DRCTEDGE,DU1507428,NaN,NaN,NaN
13,PXD,SLD,9,138.72,13:30:13,20190919,NYSE,DU1507428,NaN,NaN,NaN
14,RHI,SLD,23,55.40,13:30:13,20190919,DRCTEDGE,DU1507428,NaN,NaN,NaN
15,KLAC,SLD,8,158.10,13:30:13,20190919,ISLAND,DU1507428,NaN,NaN,NaN
16,LKQ,SLD,39,31.95,13:30:14,20190919,ISLAND,DU1507428,NaN,NaN,NaN
17,AMZN,BOT,1,1820.99,13:30:17,20190919,ARCA,DU1507428,NaN,NaN,NaN
18,CERN,SLD,100,67.85,13:30:18,20190919,NYSENAT,DU1507428,NaN,NaN,NaN
19,CERN,SLD,47,67.85,13:30:26,20190919,BATS,DU1507428,NaN,NaN,NaN
20,L,BOT,24,51.24,13:30:20,20190919,ISLAND,DU1507428,NaN,NaN,NaN
21,MOS,SLD,58,21.56,13:30:21,20190919,CHX,DU1507428,NaN,NaN,NaN
22,MOS,SLD,300,21.57,13:30:21,20190919,CHX,DU1507428,NaN,NaN,NaN
23,MOS,SLD,100,21.56,13:30:22,20190919,BYX,DU1507428,NaN,NaN,NaN
24,ED,SLD,14,91.57,13:30:21,20190919,NYSE,DU1507428,NaN,NaN,NaN
25,FANG,SLD,99,99.60,13:30:22,20190919,BYX,DU1507428,NaN,NaN,NaN
26,EMN,SLD,17,72.11,13:30:22,20190919,NYSE,DU1507428,NaN,NaN,NaN
27,AIV,SLD,24,51.94,13:30:22,20190919,ISLAND,DU1507428,NaN,NaN,NaN
28,COF,BOT,13,93.89,13:30:22,20190919,BYX,DU1507428,NaN,NaN,NaN
29,LMT,SLD,3,397.06,13:30:22,20190919,BATS,DU1507428,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
31,KR,BOT,49,25.27,13:30:34,20190919,ISLAND,DU1507428,NaN,NaN,NaN
32,MCHP,SLD,13,93.38,13:30:39,20190919,ISLAND,DU1507428,NaN,NaN,NaN
33,DVN,SLD,47,26.96,13:30:41,20190919,NYSE,DU1507428,NaN,NaN,NaN
34,TIF,BOT,13,93.61,13:30:51,20190919,ISLAND,DU1507428,NaN,NaN,NaN
35,MCO,SLD,6,216.33,13:31:29,20190919,ISLAND,DU1507428,NaN,NaN,NaN
36,SWK,SLD,9,143.28,13:31:55,20190919,BATS,DU1507428,NaN,NaN,NaN
37,FLIR,SLD,100,53.13,13:32:24,20190919,ISLAND,DU1507428,NaN,NaN,NaN
38,FLIR,SLD,90,53.13,13:33:50,20190919,ISLAND,DU1507428,NaN,NaN,NaN
39,CCL,SLD,26,48.74,13:32:31,20190919,ISLAND,DU1507428,NaN,NaN,NaN
40,PNW,BOT,13,96.07,13:32:31,20190919,ISLAND,DU1507428,NaN,NaN,NaN
41,VNO,BOT,20,63.05,13:33:00,20190919,ISLAND,DU1507428,NaN,NaN,NaN
42,SNA,SLD,8,154.88,13:33:04,20190919,BATS,DU1507428,NaN,NaN,NaN
43,TRIP,BOT,30,41.05,13:33:46,20190919,ISLAND,DU1507428,NaN,NaN,NaN
44,WLTW,SLD,6,198.29,13:34:04,20190919,ISLAND,DU1507428,NaN,NaN,NaN
45,FRC,SLD,100,96.15,13:34:07,20190919,ISLAND,DU1507428,NaN,NaN,NaN
46,FRC,SLD,5,96.15,13:34:07,20190919,ISLAND,DU1507428,NaN,NaN,NaN
47,PKG,BOT,12,104.89,13:35:39,20190919,ISLAND,DU1507428,NaN,NaN,NaN
48,DRI,BOT,80,122.98,13:42:10,20190919,ISLAND,DU1507428,NaN,NaN,NaN
49,TROW,BOT,86,116.89,13:43:51,20190919,DRCTEDGE,DU1507428,NaN,NaN,NaN
50,VIAB,BOT,48,25.81,13:46:41,20190919,ARCA,DU1507428,NaN,NaN,NaN
51,TROW,BOT,86,116.72,13:47:36,20190919,DRCTEDGE,DU1507428,NaN,NaN,NaN
52,ZBH,BOT,9,139.69,13:48:07,20190919,ISLAND,DU1507428,NaN,NaN,NaN
53,MPC,BOT,91,53.87,13:48:08,20190919,NYSE,DU1507428,NaN,NaN,NaN
54,MPC,BOT,100,53.87,13:48:08,20190919,BYX,DU1507428,NaN,NaN,NaN
55,KMX,BOT,100,85.70,13:49:12,20190919,ISLAND,DU1507428,NaN,NaN,NaN
56,KMX,BOT,16,85.70,13:49:12,20190919,ISLAND,DU1507428,NaN,NaN,NaN
57,NCLH,BOT,23,53.99,13:59:37,20190919,NYSE,DU1507428,NaN,NaN,NaN
58,TROW,SLD,86,117.08,13:59:57,20190919,ISLAND,DU1507428,NaN,NaN,NaN
59,EFX,BOT,9,141.90,14:21:44,20190919,ISLAND,DU1507428,NaN,NaN,NaN
60,ADS,BOT,10,131.17,19:32:48,20190919,ISLAND,DU1507428,NaN,NaN,NaN

Error 1100, reqId -1: La connexion entre IB et Trader Workstation a été perdue.
Error 1100, reqId -1: La connexion entre IB et Trader Workstation a été perdue.
Error 1102, reqId -1: La connexion entre IB et Trader Workstation a été restaurée et les données ont été récupérées.
Error 1100, reqId -1: La connexion entre IB et Trader Workstation a été perdue.
Error 1100, reqId -1: La connexion entre IB et Trader Workstation a été perdue.

In [22]:
megatrades.head(1)

,Underlying,Action,Quantity,Price,Time,Date,Exch.,Account,Order Ref.,Clearing,Unnamed: 10
0,SHW,SLD,19,541.75,13:30:04,20190919,ISLAND,DU1507428,NaN,NaN,NaN

In [19]:
int(''.join(stamp.split('-')))

20190918

In [18]:
type(megatrades.iloc[-1,5])

numpy.int64

In [ ]:
trades = pd.read_csv("trades."+dadato+".csv")
trades.tail()

In [ ]:


day_order = relevpoz()
day_order['Date'] = today
day_order = day_order[['Date','Compte','Type','Ticker','Quantité','Average Cost']]
try:
    day_order = day_order.drop('Unnamed: 0',axis=1)
except:
    pass
day_order.to_csv('day_order_'+today+'.csv')

In [ ]:
day_order.head()

In [ ]:
util.df(ib.positions(compte)).tail()

In [ ]:
summary = util.df(ib.accountSummary(account=compte))

In [ ]:
util.df(ib.pnl(account=compte))

In [ ]:
portfolio = util.df(ib.portfolio())
portfolio ['date'] = today
CONTRACT = []
SYMBOL = []
CONTRACT = portfolio['contract']

for i in range (0,len(CONTRACT)):
    SYMBOL.append(str(str(str(CONTRACT[i]).split(',')[1]).split('=')[1]).split("'")[1])
portfolio['contract'] = SYMBOL
portfolio = portfolio[['date','account','contract','marketPrice','marketValue','averageCost','unrealizedPNL','realizedPNL']]

In [ ]:
portfolio.head()

In [ ]:
portfolio.to_csv('portfolio_'+today+'.csv')

In [ ]:
executions = util.df(ib.executions())
executions.head()

In [ ]:
ib.pnl(ib_insync.objects.PnLSingle('dailyPnL','unrealizedPnL',compte))

In [ ]:
ib.summary(compte)

In [ ]:
summary